
server:
  port: 8081

spring:
  application:
    name: loans
  datasource:
    url: "jdbc:mysql://localhost:3306/loans"
    username: root
    password: root
    hikari:
      autoCommit: false
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      minimumIdle: 2
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: update
