build:
  version: "1.0.0"


application:
  name: loans
  message: "Welcome to Loans Microservice"
  contactDetails:
    name: "Asish-Developer"
    email: "asishm67@gmail.com"
  onCallSupport:
    - (+91) 1234567890
    - (+91) 9012345678
