
server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: "jdbc:mysql://localhost:3306/accounts"
    username: root
    password: root
    hikari:
      autoCommit: false
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      minimumIdle: 2
      maximumPoolSize: 10

